config/routes.rb
Rails.application.routes.draw do

  resources :lists  do
    resources :items, only: [:create, :destroy] do
      member do
        patch :complete
      end
    end
  end

  root 'lists#index'
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :list
  validates :content, :presence => true

  def completed?
      !completed_at.blank? # if its completed the completed field is not blank
  end
end

app/models/list.rb
class List < ActiveRecord::Base
  has_many :items

  validates :title, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_list
  before_action :set_item, except: [:create]

def create
  @item = @list.items.create(item_params)
  redirect_to @list
end

def destroy
  if @item.destroy
    flash[:success] = "Due list item deleted."
  else
    flash[:error] = "Due list item couldn't be removed."
  end
  redirect_to @list
end

def complete
  @item.update_attribute(:completed_at, Time.now)
  redirect_to @list, notice: "Due item Completed"
end


  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def set_item
    @item = @list.items.find(params[:id])
  end

  def item_params
    params[:item].permit(:content)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  def index
    @lists = List.all
  end

  def show
  end

  def new
    @list = List.new
  end

  def edit
  end

  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'Due 2 day list created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'Due 2 day list updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    if @list.items.any?
      flash[:notice] = "[ •  Remove Items from Due List First • ]"
      redirect_to @list
    else
    @list.destroy
      respond_to do |format|
        format.html { redirect_to root_url, notice: 'Due 2 day list destroyed.' }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:title, :description)
    end
end

app/views/due2day_items/_form.html.erb
<%= form_for([@due2day_list, @due2day_list.due2day_items.build]) do |f| %>
  <%= f.text_field :content, placeholder: "Enter 2 Due Item", :required => true %>
  <%= f.submit '2 Day'%>
<% end %>

app/views/due2day_lists/_form.html.erb
<%= form_for(@due2day_list) do |f| %>
  <% if @due2day_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@due2day_list.errors.count, "error") %> prohibited Due 2 Day List:</h2>

      <ul>
      <% @due2day_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, :required => true %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit 'Due 2 Day' %>
  </div>
<% end %>

app/views/due2day_lists/edit.html.erb
<h1 class="due2day_list_title">Due 2 Day</h1>

<div class="forms">
  <%= render 'form' %>
</div>

<div class="links">
  <%= link_to 'Cancel', root_url %>
</div>

app/views/due2day_lists/new.html.erb
<h1 class="due2day_list_title">Due 2 day</h1>

<div class="forms">
  <%= render 'form' %>
</div>

<div class="links">
  <%= link_to 'Back', root_url %>
</div>

app/views/items/_form.html.erb
<%= form_for([@list, @list.items.build]) do |f| %>
  <%= f.text_field :content, placeholder: "Enter 2 Due Item", :required => true %>
  <%= f.submit '2 Day'%>
<% end %>

app/views/items/_item.html.erb
<div class="row clearfix">
  <% if item.completed? %>
      <div class="complete">
        <%= link_to complete_list_item_path(@list, item.id), method: :patch do %>
          <i style="opacity: 0.4;" class="fa fa-check"></i>
        <% end %>
      </div>
      <div class="item">
        <p style="opacity: 0.4;"><strike><%= item.content %></strike> </p>
      </div>
      <div class="trash">
        <%= link_to list_item_path(@list, item.id), method: :delete do %>
        <i class="fa fa-trash"></i>
        <% end %>
      </div>
  <% else %>
      <div class="complete">
        <%= link_to complete_list_item_path(@list, item.id), method: :patch do %>
          <i class="fa fa-check"></i>
        <% end %>
      </div>
      <div class="item">
        <p><%= item.content %></p>
      </div>
      <div class="trash">
        <%= link_to list_item_path(@list, item.id), method: :delete do %>
        <i class="fa fa-trash"></i>
        <% end %>
      </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Due 2 Day</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Abel' rel='stylesheet' type='text/css'>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
</head>
<body>
<div class="container">
    <%= yield %>
</div>
</body>
</html>

app/views/lists/_form.html.erb
<%= form_for(@list) do |f| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited Due 2 Day List:</h2>

      <ul>
      <% @list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, :required => true %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit 'Due 2 Day' %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h1 class="list_title">Due 2 Day</h1>

<div class="forms">
  <%= render 'form' %>
</div>

<div class="links">
  <%= link_to 'Cancel', root_url %>
</div>

app/views/lists/index.html.erb
<% @lists.each do |list| %>
  <div class="index_row clearfix">
    <h2 class="list_title"><%= link_to list.title, list %></h2>
    <p class="list_sub_title"><%= list.description %></p>
  </div>
<% end %>

<div class="links">
  <%= link_to "New Due 2 Day", new_list_path %>
</div>

app/views/lists/new.html.erb
<h1 class="list_title">Due 2 day</h1>

<div class="forms">
  <%= render 'form' %>
</div>

<div class="links">
  <%= link_to 'Back', root_url %>
</div>

app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>

<h2 class="list_title"><%= @list.title %></h2>
<p class="list_sub_title"><%= @list.description %></p>

<div id="items_wrapper">
  <%= render @list.items %>
  <div id="form">
    <%= render "items/form" %>
  </div>
</div>

<div class="links">
  <%= link_to 'Back', root_url %> |
  <%= link_to 'Edit', edit_list_path(@list) %> |
  <%= link_to 'Delete', list_path(@list), method: :delete %>
</div>